apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "monitoring"
  TIMESCALE_HOST: "timescaledb"
  TIMESCALE_PORT: "5433"
  TIMESCALE_DB: "monitoring_metrics"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  NATS_URL: "nats://nats:4222"
  API_GATEWAY_URL: "http://api-gateway:8080"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  PROMETHEUS_PUSHGATEWAY: "http://prometheus-pushgateway:9091"
  OTLP_ENDPOINT: "tempo:4317"
  LOKI_URL: "http://loki:3100"
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
type: Opaque
stringData:
  POSTGRES_USER: monitoring
  POSTGRES_PASSWORD: changeme
  TIMESCALE_USER: monitoring
  TIMESCALE_PASSWORD: changeme
  REDIS_PASSWORD: changeme
  AUTH0_DOMAIN: your-auth0-domain.auth0.com
  AUTH0_CLIENT_ID: your-auth0-client-id
  AUTH0_CLIENT_SECRET: your-auth0-client-secret
  AUTH0_AUDIENCE: your-auth0-audience
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-observability
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:8080']
      - job_name: 'scheduler'
        static_configs:
          - targets: ['scheduler:8080']
      - job_name: 'probe-manager'
        static_configs:
          - targets: ['probe-manager:8080']
      - job_name: 'ingestion-service'
        static_configs:
          - targets: ['ingestion-service:8080']
      - job_name: 'analytics-service'
        static_configs:
          - targets: ['analytics-service:8080']
      - job_name: 'alert-manager'
        static_configs:
          - targets: ['alert-manager:8080']
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:8080']

  loki.yml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    schema_config:
      configs:
      - from: 2020-05-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    storage_config:
      boltdb:
        directory: /tmp/loki/index
      filesystem:
        directory: /tmp/loki/chunks

  tempo.yml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
    compactor:
      compaction:
        block_retention: 24h
