apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: monitoring
  labels:
    app: scheduler
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: monitoring
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: scheduler
          image: monitoring/scheduler:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: POSTGRES_DSN
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: NATS_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: probe-manager
  namespace: monitoring
  labels:
    app: probe-manager
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: probe-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-manager
  namespace: monitoring
  labels:
    app: probe-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: probe-manager
  template:
    metadata:
      labels:
        app: probe-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: probe-manager
          image: monitoring/probe-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: NATS_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-worker
  namespace: monitoring
  labels:
    app: probe-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: probe-worker
  template:
    metadata:
      labels:
        app: probe-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: probe-worker
          image: monitoring/probe-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: NATS_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: probe-worker
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: probe-worker
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
